-- this sql is intentionally kept empty
-- the purpose of this sql file is to prevent the integration test from executing the import.sql at the "main/resources", because that is meant for demo
-- for the test, the test code itself instantiates its own set of data